# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    tags:
    - 'v*'

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 使用适合的 Node.js 版本
          cache: 'pnpm'

      - name: Enable pnpm
        run: corepack enable

      - name: pnpm Version
        run: corepack prepare pnpm@10.0.0 --activate

      - name: Install Dependencies
        run: pnpm install # 或 yarn install，根据你的偏好选择

      - name: Generate Static Site
        run: pnpm run build:h5 # 或者其他生成静态站点的命令

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/build/h5'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
